import {React, useState} from "react";
import {
    useRecoilState,
  } from 'recoil';
import Typing from 'react-typing-animation';
import { cupcakes } from "../Recoil/atoms";
import Popup from 'reactjs-popup';
import 'reactjs-popup/dist/index.css';
 
function Exorcism() {
    document.title = "YOUCANNOTREMOVETHEETERNAL";

    const [cupcake, addCupcake] = useRecoilState(cupcakes);
    const [removeButton, removeButtonReveal] = useState("hidden");
    const [revealContent, changeRevealContent] = useState("hidden");
    const [revealScream, changeRevealScream] = useState("displayNone");
    const [hideConvo, changeHideConvo] = useState();

    function RemoveCupcake(x) {
            addCupcake((cake) => cake - x)
        console.log(`GLUTTONY STOLE ${x} CUPCAKE(S). YOU HAVE ${cupcake-x} cupcake(s) remaining!`)
    }    
    
    function revealButton() {
        removeButtonReveal("visible");
    }

    return (
        <div>
      <div className={`exorcism ${hideConvo}`}>
        <Typing onFinishedTyping={()=> RemoveCupcake(5)}>
            <h2>I WILL DEVOUR YOU, JILLIAN EVANS. YOUR SOUL IS ALREADY MINE</h2>
            <Typing.Delay ms={1000} />
            <p>You may have destroyed my body, but my soul belongs to no one.</p>
            <Typing.Delay ms={500} />
            <h2>YOU CANNOT ESCAPE ME. RESIGN TO YOUR FATE AND BECOME ONE WITH GLUTTONY</h2>
            <Typing.Delay ms={500} />
            <p>I reject you from this website, and I cast you out into the dark unknown. Where you belong.</p>
            <Typing.Delay ms={500} />
            <Typing.Speed ms={5}/>
            
            <h2>DIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIE
                DIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIEDIE
            </h2>
            <Typing.Delay ms={500} />
            <p>Be gone, beast. Ruin no other lives.</p>
            <Typing.Delay ms={500}/>
            <h1>DIE</h1>
        </Typing>
        <Typing startDelay={33000} onFinishedTyping={()=>RemoveCupcake(1)}>
            <p>You will not defeat me or our visitor, beast. Silence.</p>
            <h1>DIE</h1>
        </Typing>
        <Typing startDelay={38000} onFinishedTyping={()=>RemoveCupcake(1)}>
            <p>I said silence. Leave this place.</p>
            <h1>DIE</h1>
        </Typing>
        <Typing startDelay={42000} onFinishedTyping={()=>{RemoveCupcake(3); revealButton()}}>
            <p>I said SILENCE</p>
            <h1>DIE DIE DIE! DIE!</h1>
        </Typing>

        <Popup
    trigger={<button className={`${removeButton}`}>Delete GLUTTONY</button>}
    modal
    nested
  >
    {close => (
      <div className="modal">
        <span className="exorcism">
            <h2>LISTEN TO ME. I CAN GRANT YOU LIFE EVERLASTING</h2>
            <button onClick={() => changeRevealContent("visible")}>Delete GLUTTONY</button>
            <span className={`${revealContent}`}>
              <h2>NO. FOOL. YOU WILL PAY FOR THIS</h2>
            </span>
        </span>
        <div className="actions">
          <button
            className={`button ${revealContent}`}
            onClick={() => {
              close();
              changeRevealScream("displaySome");
              changeHideConvo("displayNone")
            }}
          >
            EXORCISE
          </button>
        </div>
      </div>
    )}
  </Popup>

      </div>
      <div className={`${revealScream} exorcism`}>
      <article>
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
         AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        </article>
      </div>
      </div>
    );
  }
 
export default Exorcism;