import React from "react";
import {
  NavLink,
} from "react-router-dom";
import "../index.css";

import { randomavatar, humanmouth, thingmouth, sharkmouth } from "../img/index";
 
function Recipe19() {

    document.title = "FAMELICUS";

    return (
      <div>
        <div id="recipe">
        <h2>Recipe Name</h2>
        <h3>September, 2021 By <NavLink to="/aboutme">litatio</NavLink>. 0 Comments ↓</h3>
        <p> 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
          FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        </p>
        <img width="50%" src ={humanmouth} alt="IMG 1"></img>
        <p>
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        </p>
        <img width="50%" src={thingmouth} alt="IMG 2"></img>
        <p>
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        </p>
        <img width="50%" src={sharkmouth} alt="IMG 3"></img>
        <p>
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        </p>
        <img width="10%" alt="IMG 4"></img>
        <p>
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        </p>
        <img width="10%" alt="IMG 5"></img>
        <p>
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS  FAMELICUS 
        </p>
        <h3>FAMELICUS</h3>
        <p>FAMELICUS FAMELICUS FAMELICUS</p>
        <ul>
          <li>FAMELICUS</li>
          <li>FAMELICUS</li>
          <li>FAMELICUS</li>
          <li>FAMELICUS</li>
          <li>FAMELICUS</li>
        </ul>
        <p>FAMELICUS</p>
        <p>FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS
        FAMELICUS FAMELICUS FAMELICUS

        </p>
        <p>FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS
        </p>
        <p>FAMELICUS FAMELICUS FAMELICUS FAMELICUS
        </p>
        <p>FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS
        </p>
        <p>FAMELICUS FAMELICUS FAMELICUS FAMELICUS
        </p>
        <p id="commentSection">Comments</p>
        </div>

          <ul className="commentSection">

            <li>
              <img src={randomavatar}alt="random avatar"></img>
              <p className="username">FAMELICUS - September, 2021 :</p>
              <p>FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS FAMELICUS </p>
            </li>
          </ul>

      </div>
    );
  }
 
export default Recipe19;